kind: pipeline
name: default

steps:
  - name: test
    image: golang:1.17.0
    environment:
      HTTP_PROXY: "http://proxy.iiji.jp:8080"
      HTTPS_PROXY: "http://proxy.iiji.jp:8080"
      DB_ROLE: testuser
      DB_PASSWORD: testuser
      DB_NAME: mdtd_bootcamp
      DB_HOST: mysql
      DB_PORT: 3306
      DATA_SOURCE_NAME: "testuser:testuser@tcp(mysql:3306)/mdtd_bootcamp"
    commands:
      - go get golang.org/x/lint/golint
      - apt-get update && apt-get install default-mysql-client -y
      - while [ -n "$(mysqladmin -utestuser -ptestuser ping -h mysql 2>&1 > /dev/null)" ]; do sleep 1; done
      - mysql -hmysql -utestuser -ptestuser mdtd_bootcamp < table_create.sql
      - go fmt ./...
      - go vet ./...
      - golint ./...
      - go test ./...

services:
  - name: mysql
    image: mysql:5.7.33
    command: [ "--character-set-server=utf8", "--collation-server=utf8_unicode_ci", "--explicit_defaults_for_timestamp=true", "--skip-character-set-client-handshake", "--character-set-filesystem=utf8" ]
    environment:
      MYSQL_USER: 'testuser'
      MYSQL_PASSWORD: 'testuser'
      MYSQL_DATABASE: "mdtd_bootcamp"
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    port:
      3306
