openapi: 3.0.3
info:
  version: 1.0.0
  title: shopping API
  
tags:
  - name: shopping
    description: shopping API

paths:
  /api/shopping:
    post:
      tags:
        - shopping
      description: |
        買い物リストを作成する
        
      requestBody:
        content:
          application/json:
            schema:
              properties:
                shopping_day:
                  type: string
                product_name:
                  type: string
                quantity:
                  type: string
                price:
                  type: string
              example:
                shopping_day: "20200720"
                product_name: "にんじん"
                quantity: "1袋"
                price: "190円"
                
                
                
                
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                properties:
                  shopping_day:
                   type: string
                  product_name:
                   type: string
                  quantity:
                   type: string
                  price:
                   type: string
                  shopping_id:
                   type: integer

              example:
                
                shopping_id: 1
                shopping_day: "20200720"
                product_name: "にんじん"
                quantity: "1袋"
                price: "190円"

        "400":
          description: Bad Request
          
        "409":
          description:  Conflict 
          
        "500":
          description: Internal Server Error
          
          
          
          
    get:
      tags:
        - shopping
      description: |
        全買い物リストを参照する
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                 properties:
                  shopping_day:
                   type: string
                  product_name:
                   type: string
                  quantity:
                   type: string
                  price:
                   type: string
                  shopping_id:
                   type: integer

              example:     
          
              - shopping_id: 1
                shopping_day: "20200720"
                product_name: "にんじん"
                quantity: "1袋"
                price: "190円"

              - shopping_id: 2
                shopping_day: "20200721"
                product_name: "たまねぎ"
                quantity: "1袋"
                price: "210円"

              - shopping_id: 3
                shopping_day: "20200722"
                product_name: "じゃがいも"
                quantity": null
                price: null
          
          
  /api/shopping/{shopping_id}:
    patch:
      tags:
        - shopping
      description: 指定した買い物リストの日付を変更する
      parameters:
        - name: shopping_id
          in: path
          description: 買い物リストのID
          required: true
          schema:
           type: integer
           
           
      requestBody:
        content:
          application/json:
            schema:
              properties:
                shopping_day:
                  type: string
              example:
                shopping_day: "20200724"
                    
           
           
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                properties:
                  shopping_day:
                   type: string
                  shopping_id:
                   type: integer
                   
              example:    
                shopping_id: 1
                shopping_day: "20200724" 
          
        "400":
          description: Bad Request
          
        "404":
          description: Not Found
          
        "500":
          description: Internal Server Error  
    
    
    
    delete:
      tags:
        - shopping
      description: 指定した買い物リストの価格を削除する
      parameters:
        - name: shopping_id
          in: path
          description: 買い物リストのID
          required: true
          schema:
           type: integer
        
     
      responses:    
        
        "204":
          description: No content
          
        "404":
          description: Not Found
          
        "500":
          description: Internal Server Error
    
    
    
    
    
  
  
  
  
  
          
          
  /api/shopping/{shopping_id}/products/{shopping_product_id}:
    patch:
      tags:
        - shopping
      description: 指定した買い物リストの商品、個数、価格を変更する
      parameters:
        - name: shopping_id
          in: path
          description: 買い物リストのID
          required: true
          schema:
           type: integer
        
        - name: shopping_product_id
          in: path
          description: 買い物リストの商品のID
          required: true
          schema:
           type: integer   
           
      requestBody:
        content:
          application/json:
            schema:
              properties:
                product_name:
                  type: string
                quantity:
                  type: string
                price:
                  type: string
                  
              example:
                 product_name: "豚肉"
                 quantity: "100g"
                 price: "240円"
                    
        required: true   
           
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
               properties:
                product_name:
                   type: string
                quantity:
                   type: string
                price:
                   type: string
                shopping_id:
                   type: integer
                   
              example:    
                shopping_id: 1
                product_name: "豚肉"
                quantity: "100g"
                price: "240円"
                
          
          
        "400":
          description: Bad Request
          
        "404":
          description: Not Found
          
        "500":
          description: Internal Server Error        
          
    post:
      tags:
        - shopping
      description: 指定した買い物リストの商品を追加する
      parameters:
        - name: shopping_id
          in: path
          description: 買い物リストのID
          required: true
          schema:
           type: integer
        
        - name: shopping_product_id
          in: path
          description: 買い物リストの商品のID
          required: true
          schema:
           type: integer   
           
      requestBody:
        content:
          application/json:
            schema:
              properties:
                product_name:
                  type: string
                
                  
              example:
                 product_name: "たまねぎ"
                 
                    
        required: true   
           
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
               properties:
                product_name:
                   type: string
                quantity:
                   type: string
                price:
                   type: string
                shopping_id:
                   type: integer
                shopping_day:
                   type: string
                
                
                   
              example:
              
               - shopping_id: 1
                 shopping_day: "20200720"
                 product_name: "にんじん"
                 quantity: "1袋"
                 price: "190円"

               - shopping_id: 1
                 shopping_day: "20200720"
                 product_name: "たまねぎ"
                 
          
          
        "400":
          description: Bad Request
          
        "404":
          description: Not Found
          
        "500":
          description: Internal Server Error      
          
          
          
  /api/shopping/{shopping_id}/products/{shopping_product_id}/product_name:
    delete:
      tags:
        - shopping
      description: 指定した買い物リストの商品を削除する
      parameters:
        - name: shopping_id
          in: path
          description: 買い物リストのID
          required: true
          schema:
           type: integer
        
        - name: shopping_product_id
          in: path
          description: 買い物リストの商品のID
          required: true
          schema:
           type: integer   
           
     
      responses:    
        
        "204":
          description: No content
          
        "404":
          description: Not Found
          
        "500":
          description: Internal Server Error        
          
  
  
  /api/shopping/{shopping_id}/products/{shopping_product_id}/quantity:
    delete:
      tags:
        - shopping
      description: 指定した買い物リストの個数を削除する
      parameters:
        - name: shopping_id
          in: path
          description: 買い物リストのID
          required: true
          schema:
           type: integer
        
        - name: shopping_product_id
          in: path
          description: 買い物リストの商品のID
          required: true
          schema:
           type: integer   
           
     
      responses:    
        
        "204":
          description: No content
          
        "404":
          description: Not Found
          
        "500":
          description: Internal Server Error 
  
  
  
  /api/shopping/{shopping_id}/products/{shopping_product_id}/price:
    delete:
      tags:
        - shopping
      description: 指定した買い物リストの価格を削除する
      parameters:
        - name: shopping_id
          in: path
          description: 買い物リストのID
          required: true
          schema:
           type: integer
        
        - name: shopping_product_id
          in: path
          description: 買い物リストの商品のID
          required: true
          schema:
           type: integer   
           
     
      responses:    
        
        "204":
          description: No content
          
        "404":
          description: Not Found
          
        "500":
          description: Internal Server Error
  
